#!/bin/bash

### BEGIN INIT INFO
# Provides:             x11vnc
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    x11vnc
### END INIT INFO

case "$1" in
start)
  pid="$(pidof x11vnc)"
  if [[ $? -eq 0 && "$pid" != "" ]];then
    echo "Start x11vnc: already started"
  else
    x11vnc -bg -display :0 -forever -rfbauth ~/.vnc/passwd --noipv6 -no6 --scale 1552x1000
    sleep 2
    echo "Start x11vnc: $(pidof x11vnc)"
  if
  ;;
stop)
  pid="$(pidof x11vnc)"
  if [[ $? -eq 0 && "$pid" != "" ]];then
    echo "Stop x11vnc: $pid."
    kill -9 $pid
  else
    echo "Stop x11vnc: not running"
    exit 1
  fi
  ;;
*)
  echo "Usage: service x11vnc {start|stop}"
  exit 1
;;
esac
